name: Update Streak Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: pip install -r requirement.txt

    - name: Track Streak
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python send_problems.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update daily streak chart"
        git push
